// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9btXLQeL9U2Pj0DJFKrO8Fcg0QcvKuGc',
    appId: '1:1021282474986:web:c95126574a5f7080073093',
    messagingSenderId: '1021282474986',
    projectId: 'rentit-b7a3e',
    authDomain: 'rentit-b7a3e.firebaseapp.com',
    storageBucket: 'rentit-b7a3e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8HXjCfXMWqfU5qneOq7ouz8SUYsGuMUU',
    appId: '1:1021282474986:android:eabf57f402d66848073093',
    messagingSenderId: '1021282474986',
    projectId: 'rentit-b7a3e',
    storageBucket: 'rentit-b7a3e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCatRoeGIWPr5_dhULv9lo6AA84ajdFvSw',
    appId: '1:1021282474986:ios:9b8fbbeedfe19625073093',
    messagingSenderId: '1021282474986',
    projectId: 'rentit-b7a3e',
    storageBucket: 'rentit-b7a3e.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCatRoeGIWPr5_dhULv9lo6AA84ajdFvSw',
    appId: '1:1021282474986:ios:9b8fbbeedfe19625073093',
    messagingSenderId: '1021282474986',
    projectId: 'rentit-b7a3e',
    storageBucket: 'rentit-b7a3e.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9btXLQeL9U2Pj0DJFKrO8Fcg0QcvKuGc',
    appId: '1:1021282474986:web:0681953ce3fba82b073093',
    messagingSenderId: '1021282474986',
    projectId: 'rentit-b7a3e',
    authDomain: 'rentit-b7a3e.firebaseapp.com',
    storageBucket: 'rentit-b7a3e.appspot.com',
  );
}
